### ISSUE TITLE
Bad characters in Talks section

### ISSUE THREAD

**Issue by feststelltaste** [dukecon/dukecon#55]
In the "Talks" section, there are some special characters that

- aren't displayed in Firefox (Version 62, Windows 10) at all:
![grafik](https://user-images.githubusercontent.com/1470822/46036692-7283b980-c106-11e8-8972-5e81f157f850.png)

- are replaced by placeholder symbols in Chrome (Version 69, for both Windows 10 and Android 8)
![grafik](https://user-images.githubusercontent.com/1470822/46036814-cababb80-c106-11e8-92ea-8bdae7a86811.png)

**Comment by sippsack** [comment]
The data comes from the DOAG conference system as an ANSI encoded JSON file, as Notepad++ says:

![image](https://user-images.githubusercontent.com/413426/46046704-5b52c500-c122-11e8-9497-221fd79bc169.png)

DukeCon reads this json file with a Groovy JsonSlurper in ISO-8859-1 which already seems to fail:

![image](https://user-images.githubusercontent.com/413426/46046786-a53bab00-c122-11e8-9b41-acd8f4dca3a8.png)

So the quick fix would be to replace the wrong encode character right in the DOAG conference system with a standard ASCII apostroph.

I'm not sure how to find out the correct encoding of this json file in order to read it properly.

**Comment by feststelltaste** [comment]
Maybe this could "work around" the problem, but it seems that there are more characters that aren't working correctly:

![chrome69_win10_gerd](https://user-images.githubusercontent.com/1470822/46068935-9d0f5a00-c17a-11e8-802d-bb1b47ba8759.png)

**Comment by sippsack** [comment]
the "Klassiker": apostroph and hyphens ...

**Comment by sippsack** [comment]
This issue was moved to dukecon/dukecon_server#82
